name: Apply Template to Repos

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Template Repo
        uses: actions/checkout@v2
        with:
          repository: vijayakumari2/template-repo
          path: template-repo

      - name: Push Template to Repos
        run: |
          TEMPLATE_REPO="vijayakumari2/template-repo"
          REPOS=$(gh repo list vijayakumari2 --json name -q '.[].name')
          for REPO in $REPOS; do
            if [ "$REPO" != "${TEMPLATE_REPO#*/}" ]; then
              echo "Processing $REPO..."
              git clone https://github.com/vijayakumari2/$REPO.git
              cp -r template-repo/.github/workflows $REPO/.github/workflows
              cd $REPO
              git add .github/workflows
              git commit -m "Apply template from $TEMPLATE_REPO"
              git push origin main
              cd ..
              rm -rf $REPO
            else
              echo "Skipping template repository $REPO"
            fi
          done
